apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: python
  namespace: utherp0
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: uthapp2
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: python
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: python-
      labels:
        build.appstudio.openshift.io/application: uthapp2
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: python
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: utherp0
    spec:
      params:
      - name: git-url
        value: https://github.com/maysunfaisal/multi-components-dockerfile
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:utherp0-python-$(tt.params.git-revision)
      - name: dockerfile
        value: https://raw.githubusercontent.com/maysunfaisal/multi-components-dockerfile/main/devfile-sample-python-basic/Dockerfile
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: python/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
